version: "2.4"

services:

  cloud:
    image: nextcloud
    ports:
      - 80:80
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ncdata
      POSTGRES_USER: turtlebasket
      POSTGRES_PASSWORD: pass

  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: ncdata
      POSTGRES_USER: turtlebasket
      POSTGRES_PASSWORD: pass

